### ISSUE TITLE
'PORTB' was not declared in this scope

### ISSUE THREAD

**Issue by joeycortez42** [bjpirt/HotStepper#1]
I'm looking for a ESP8266 friendly stepper library, but when I try one of your examples I get the following error:
`Arduino/libraries/HotStepper/HotStepper.h:57:4: error: expected constructor, destructor, or type conversion before '(' token
 ISR(TIMER2_COMPA_vect)
    ^
HotStepper:5: error: 'PORTB' was not declared in this scope
 HotStepper stepper1(&PORTB, 0b00011101);
                      ^
HotStepper:6: error: 'PORTD' was not declared in this scope
 HotStepper stepper2(&PORTD, 0b11110000);
                      ^
exit status 1
'PORTB' was not declared in this scope`

I looked at the cpp file and it looks like those should be a constant of some kind. What am I doing wrong? 

Thanks!

**Comment by bjpirt** [comment]
I'm afraid this library is currently AVR only. Sorry about that.
